# Cloud Build configuration - Ejemplo básico
# Construye imagen Docker y la publica en Artifact Registry
# Nota: SHORT_SHA solo está disponible cuando se ejecuta desde un trigger de Git
# Para ejecución manual, se usa BUILD_ID directamente en los tags
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/app-info-service:${BUILD_ID}'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/app-info-service:latest'
      - '.'
    dir: 'materiales/practica-4/ejemplo-migracion-completa'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/app-info-service'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/app-info-service:${BUILD_ID}'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'APP_NAME=${_APP_NAME},ENVIRONMENT=${_ENVIRONMENT}'
      - '--update-secrets'
      - 'SECRET_MESSAGE=${_SECRET_NAME}:latest'

images:
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/app-info-service:${BUILD_ID}'
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/app-info-service:latest'

substitutions:
  _REGION: 'europe-southwest1'
  _REPO_NAME: 'docker-repo'
  _SERVICE_NAME: 'app-info-service'
  _APP_NAME: 'App Info Service'
  _ENVIRONMENT: 'production'
  _SECRET_NAME: 'secret-message'
  # _IMAGE_TAG: Para ejecución manual usa BUILD_ID directamente (BUILD_ID siempre está disponible).
  # Para triggers de Git, puedes cambiar esto a '${SHORT_SHA}' o pasar --substitutions=_IMAGE_TAG=${SHORT_SHA}
  # IMPORTANTE: BUILD_ID se usa directamente, no dentro de una substitution porque no se expande
  #_IMAGE_TAG: '${BUILD_ID}'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

timeout: '1200s'
